# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: [self-hosted k8s-api ubuntu:latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    # - name: Setup make
    #   uses: actions/setup-make
    - name: Build
      run: Make
    - name: List files in the repository
      run: |
        ls -l

